### ISSUE TITLE
Unable to import from_schema from hypothesis_graphql

### ISSUE THREAD

**Issue by Sukeerthi31** [Stranger6667/hypothesis-graphql#105]
**Describe the bug**
Unable to import from_schema from hypothesis_graphql

**To Reproduce**
Steps to reproduce the behaviour:

1. My GraphQL schema is - the sample schema provided in the README
2. Run this command - python3 hypothesis_graphql.py 
3. See error - 
ImportError: cannot import name 'from_schema' from partially initialized module 'hypothesis_graphql' (most likely due to a circular import) (file-path/hypothesis_graphql.py)

**Expected behavior**
Imports to go through correctly

**Environment (please complete the following information):**

- OS: Mac
- Python version: 3.9.6 and also noticed with 3.11.1
- hypothesis-graphql version: 0.11.0
- hypothesis version: 6.100.0

**Comment by Stranger6667** [comment]
This issue is not relevant to `hypothesis_graphql`. The same could be achieved with `sample.py`:

```python
from sample import foo


def foo():
    print("Hello from foo!")
```

```bash
> python sample.py
Traceback (most recent call last):
  File "/tmp/sample.py", line 1, in <module>
    from sample import foo
  File "/tmp/sample.py", line 1, in <module>
    from sample import foo
ImportError: cannot import name 'foo' from partially initialized module 'sample' (most likely due to a circular import) (/tmp/sample.py)
```

**Comment by Stranger6667** [comment]
I.e. you should not name your sample file the same as the module you have imports from.
