### ISSUE TITLE
Verify shrinking behavior

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/hypothesis-graphql#16]
I am not sure how good shrinking works with the current implementation and if it could be improved. We can try to build some app first, add a target error and check how good it will be in finding a minimal example. 

There is no concrete plan on my mind now since I don't have much experience with Hypothesis internals, maybe we can get some advice from Hypothesis devs

**Comment by Zac-HD** [comment]
`hypothesis.find()` is probably sufficient, if you can generate schemas and calculate the minimal value for various predicates (e.g. lists containing an integer -> `[0]`).

**Comment by Stranger6667** [comment]
Aha, thank you, Zac! :) I'll try digging that
