### ISSUE TITLE
[BUG] When an input object has an optional enum argument, one of the generated values is "EnumValueNode"

### ISSUE THREAD

**Issue by dkbarn** [Stranger6667/hypothesis-graphql#32]
There is a bug that occurs when a GraphQL schema has an optional enum argument on an input object. One of the values that hypothesis-graphql generates is: ```EnumValueNode```. I'm guessing that this is happening during the case when the enum value is supposed to be null.

To demonstrate, run the following with ```pytest -s```:
```
import schemathesis

schema = schemathesis.graphql.from_file(
    """
    enum MyEnum {
        FOO
        BAR
        BAZ
    }
    
    input MyInput {
        value: MyEnum
    }
    
    type Query {
        hello(i: MyInput!): String
    }
    """
)

@schema.parametrize()
def test_schema(case):
    print(case.body)
```

The printed output is the following:
```
{
  hello(i: {value: FOO})
}

{
  hello(i: {value: EnumValueNode})
}

{
  hello(i: {value: BAZ})
}

{
  hello(i: {value: FOO})
}

{
  hello(i: {value: BAR})
}
```

I am using:
schemathesis 3.6.3
hypothesis-graphql 0.4.1
graphql-core 3.1.4

**Comment by Stranger6667** [comment]
Thanks for a great report! I will take a look at it today/tomorrow

**Comment by Stranger6667** [comment]
As far as I understand, the following query will be valid, right?

```graphql
{
  hello(i: {value: null})
}
```

**Comment by dkbarn** [comment]
> As far as I understand, the following query will be valid, right?
> 
> ```graphql
> {
>   hello(i: {value: null})
> }
> ```

Yes that's correct.

Thanks for the quick fix!

**Comment by Stranger6667** [comment]
You're welcome :) I'll make a release today / tomorrow
